[profile.default]
src = "src"
out = "foundry/out"
cache_path = "foundry/cache"
test = "tests"
libs = ["node_modules", "foundry/lib"]
optimizer = true
optimizer_runs = 100
evm_version = "cancun"
ffi = true                             # required by hedera-forking
allow_internal_expect_revert = true
show_logs = true

[fuzz]
runs = 100
seed = '0xc0ffee' # Seed for reproducibility
show_logs = true

[invariant]
runs = 50         # Number of tests to run
depth = 100       # Number of function calls in each test
seed = '0xc0ffee' # Seed for reproducibility
show_logs = true
